#!/bin/bash
#
# packs386
# (c) 2011 Alf Gaida <info@g-com.eu>
# 

export TMPSCRIPT=/tmp/packs-script-$(whoami)
export OLDGNUPGHOME=${GNUPGHOME}
export ARCH="i386"
export BUILDER=$(whoami)


if [ -f ~/.pbuilderrc ]; then
    . ~/.pbuilderrc
fi

export GNUPGHOME=${OLDGNUPGHOME}

cat ~/.bashrc > $TMPSCRIPT
echo "cd ${BUILDRESULT}" >> $TMPSCRIPT
echo "SAVEPS=${PS1}" >> $TMPSCRIPT
echo "export PS1='\[\033[1;33m\]pbuilder-shell. Leave with exit:\w \$\[\033[0m\] '" >> $TMPSCRIPT
bash --rcfile $TMPSCRIPT


