#!/bin/bash
#
# packs
# (c) 2011 Alf Gaida <info@g-com.eu>
#
BUILDER=$(whoami)

if [ -f /etc/pbuilderrc ]; then
  BUILDRC="GLOBAL"
fi

if [ -f ~/.pbuilderrc ]; then
  BUILDRC="USER"
fi


if [ -f ./.pbuilderrc ]; then
  BUILDRC="DIR"
fi


if [ -f ~/.debuildrc ]; then
  DEBUILDRC="USER"
fi


if [ -f ./.debuildrc ]; then
  DEBUILDRC="DIR"
fi



case $BUILDRC in
"GLOBAL")
  echo 'use /etc/pbuilderrc'
    ;;
"USER")
    echo 'use ~/.pbuilderrc'
    . ~/.pbuilderrc
    ;;
"DIR")
    echo 'use /$dir/.pbuilderrc'
    . ./.pbuilderrc
    ;;
*)
    echo "not configured, please conigure pbuilder"
    break
    ;;
esac

case $DEBUILDRC in
"USER")
    echo 'use ~/.debbuildrc'
    . ~/.debbuildrc
    ;;
"DIR")
    echo 'use /$dir/.debuildrc'
    . ./.debuildrc
    ;;
*)
    echo 'not configured, please configure ~/.debbuildrc oder /$dir/.debbuildrc'
    ;;
esac

TMPSCRIPT=/tmp/packs-script-${BUILDER}
ARCH="amd64"

cat ~/.bashrc > $TMPSCRIPT
echo "cd ${BUILDRESULT}" >> $TMPSCRIPT
echo "SAVEPS=${PS1}" >> $TMPSCRIPT
echo "export PS1='\[\033[1;33m\]pbuilder-shell. Leave with exit:\w \$\[\033[0m\] '" >> $TMPSCRIPT
bash --rcfile $TMPSCRIPT
rm $TMPSCRIPT


