#!/bin/bash
#
# pbuild
# (c) 2011 Alf Gaida <info@g-com.eu>
# 

export BUILDER=$(whoami)
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"
export AUTO_DEBSIGN=yes
export DEBSIGN_PROGRAM=gpg
export DEBSIGN_ALWAYS_RESIGN=yes

export ARCH="amd64"
sudo -E pbuilder --build ${@}

export GNUPGHOME=${OLDGNUPGHOME}
