#!/bin/bash
#
# pcreate 
# (c) 2011 Alf Gaida <info@g-com.eu>
# 
export OLDHOME=${HOME}
export OLDGNUPGHOME=${GNUPGHOME}

export HOME="/root"
export GNUPGHOME="/root/.gnupg"

export ARCH="amd64"
sudo -E pbuilder --create ${@}

export HOME=${OLDHOME} 
export GNUPGHOME=${OLDGNUPGHOME}