#!/bin/bash
#
# pcreate386 
# (c) 2011 Alf Gaida <info@g-com.eu>
# 
export BUILDER=$(whoami)
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

export ARCH="i386"
sudo -E pbuilder --create ${@}

export GNUPGHOME=${OLDGNUPGHOME}
