#!/bin/bash
#
# plogin386
# (c) 2011 Alf Gaida <info@g-com.eu>
#
export BUILDER=$(whoami)
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

export ARCH="i386"
export debian_chroot="pbuild-i386 $$"
sudo -E pbuilder --login ${@}

export GNUPGHOME=${OLDGNUPGHOME}
