#!/bin/bash
#
# pupdate
# (c) 2011 Alf Gaida <info@g-com.eu>
#
export BUILDER=$(whoami)
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

export ARCH="amd64"
sudo -E pbuilder --update --override-config ${@}

export GNUPGHOME=${OLDGNUPGHOME}
