#!/bin/bash
#
# pupdate386
# (c) 2011 Alf Gaida <info@g-com.eu>
# 
export OLDHOME=${HOME}
export OLDGNUPGHOME=${GNUPGHOME}

export HOME="/root"
export GNUPGHOME="/root/.gnupg"

export ARCH="i386"
sudo -E pbuilder --update --override-config ${@}

export HOME=${OLDHOME} 
export GNUPGHOME=${OLDGNUPGHOME}
