#!/bin/bash
#
# pbuild
# (c) 2011-2012 Alf Gaida <agaida@siduction.org>
#

. /usr/share/pbuilder-scripts/set_pbuilder
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

export ARCH="amd64"
sudo -E pbuilder --build ${@}

export GNUPGHOME=${OLDGNUPGHOME}
