#!/bin/bash
#
# pcreate386
# (c) 2011-2012 Alf Gaida <agaida@siduction.org>
#
. /usr/share/pbuilder-scripts/set_pbuilder
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

export ARCH="i386"
sudo -E pbuilder --create ${@}

export GNUPGHOME=${OLDGNUPGHOME}
