#!/bin/bash
#
# pcreate
# (c) 2011-2012 Alf Gaida <agaida@siduction.org>
#
export ARCH="amd64"
. /usr/share/pbuilder-scripts/set_pbuilder
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

sudo -E pbuilder --create ${@}

export GNUPGHOME=${OLDGNUPGHOME}
