#!/bin/bash
#
# plogin386
# (c) 2011-2012 Alf Gaida <agaida@siduction.org>
#
export ARCH="i386"
. /usr/share/pbuilder-scripts/set_pbuilder
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

export debian_chroot="pbuild-i386 $$"
sudo -E pbuilder --login ${@}

export GNUPGHOME=${OLDGNUPGHOME}
