#!/bin/bash
#
# plogin
# (c) 2011-2012 Alf Gaida <agaida@siduction.org>
#
. /usr/share/pbuilder-scripts/set_pbuilder
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

export ARCH="amd64"
export debian_chroot="pbuild-amd64 $$"
sudo -E pbuilder --login ${@}

export GNUPGHOME=${OLDGNUPGHOME}
