#!/bin/bash
#
# pupdate
# (c) 2011 Alf Gaida <info@g-com.eu>
#
export ARCH="amd64"
. /usr/share/pbuilder-scripts/set_pbuilder
export OLDGNUPGHOME=${GNUPGHOME}
export GNUPGHOME="/home/${BUILDER}/.gnupg"

sudo -E pbuilder --update --override-config ${@}

export GNUPGHOME=${OLDGNUPGHOME}
